services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27018:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=orderms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=orderms'
      - 'MONGO_INITDB_ROOT_USERNAME=orderms'

  rabbitmq:
    image: 'rabbitmq:3.13.7-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=orderms'
      - 'RABBITMQ_DEFAULT_USER=orderms'
    ports:
      - '15672:15672'
      - '5672:5672'
