services:
  app:
    container_name: "orderms_api"
    build:
      context: ./
      dockerfile: Dockerfile
    image: svt/desafio_btg_pactual
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=orderms_db
      - DB_USERNAME=orderms
      - DB_PASSWORD=orderms
    networks:
      - app_network

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27018:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=orderms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=orderms'
      - 'MONGO_INITDB_ROOT_USERNAME=orderms'
    networks:
      - app_network

  rabbitmq:
    image: 'rabbitmq:3.13.7-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=orderms'
      - 'RABBITMQ_DEFAULT_USER=orderms'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
