spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: mongodb
      port: 27017
      database: orderms_db
      username: orderms
      password: orderms

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: orderms
    password: orderms
